server:
  port: 9091

spring:
  application:
    name: Auth
  main:
    allow-bean-definition-overriding: true
  data.mongodb.uri: mongodb+srv://chami:chami@cluster0.82inl5q.mongodb.net/auth
  data.mongodb.database: auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka

